import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '베타 테스트 안내 | 충주 할배 Korean Names',
  description: '팀원과 영어 사용자에게 공유할 무료 베타 테스트 안내입니다.',
  robots: { index: false, follow: false },
};
export default function BetaGuide() {
  return <main className="names-site beta-info-page beta-guide" lang="ko">
    <header className="site-header"><a className="brand" href="/"><span><strong>충주 할배</strong><small>· GWIMUN SAJU ·</small></span></a></header>
    <article className="beta-info-card"><p className="eyebrow">TEAM BETA · 무료 공개 테스트</p><h1>팀원용 베타 테스트 안내</h1><p>해외 거주 영어 사용자가 본명·생년월일·원하는 뜻과 느낌을 바탕으로 한국 이름을 찾아보는 서비스입니다. 아래 버튼과 이 안내 링크를 그대로 팀원에게 공유하면 됩니다. 로그인은 필요 없습니다.</p><a className="hero-cta" href="/">영어 베타 열기 →</a>
      <h2>약 5분이면 테스트할 수 있어요</h2><ol className="plan-steps"><li>평소 불리는 이름을 입력하고 양력 생년월일을 연·월·일로 직접 입력합니다. 공개 테스트에 실제 생일을 쓰고 싶지 않으면 가상의 정보를 사용하세요.</li><li>출생시간은 모르면 비워 둡니다. 시간을 알면 태어난 지역의 시간대를 선택합니다.</li><li>원하는 뜻을 영어로 쓰고 분위기와 여성적·남성적·중성적 인상을 선택합니다. 성별을 추정하는 기능은 아닙니다.</li><li><span lang="en">Familiar / Timeless / Contemporary</span> 방향을 바꿔 보고, 이름과 추천 이유가 원하는 느낌에 맞는지 살펴봅니다.</li><li>이름을 고른 뒤 개인 보고서·한국어 자기소개·PNG 카드·PDF 인쇄를 확인합니다. 다른 후보를 요청하면 이번 세션에서 본 이름을 제외합니다.</li><li>후보 2~3개로 친구 투표 링크를 만들고 다른 브라우저에서 열어 보세요. 친구 화면에는 후보 이름과 로마자 표기만 나와야 합니다. 재투표하면 첫 표가 유지됩니다.</li><li>결과 아래 <span lang="en">Send feedback</span>으로 평점과 의견을 남깁니다. 어색한 이름·성별 인상·영어 문구·발음 문제를 구체적으로 적어 주세요. 본명·생일 등 개인정보는 쓰지 마세요.</li></ol>
      <h2>팀에서 특히 봐주세요</h2><ul className="guide-list"><li><strong>한국어 검수:</strong> 실제 한국인이 사용하는 이름처럼 자연스러운가? 성인에게 어색하지 않은가? 남성적·여성적·중성적 설명이 납득되는가?</li><li><strong>영어 검수:</strong> 단어 뜻과 이름의 인상을 혼동하지 않는가? 추천 이유가 입력과 맞는가? 영어만 읽어도 사용법을 이해할 수 있는가?</li><li><strong>사용성:</strong> 휴대폰에서 생일 입력·선택·재추천·공유·다운로드가 쉬운가? 한국어 음성은 기기에 한국어 음성이 설치되어 있어야 합니다.</li></ul>
      <h2 id="quality">확인된 것과 검수가 필요한 것</h2><p>총 2,119개 이름 자료 중 기본 추천에는 796개를 사용합니다. 대부분 합성 한국인 페르소나 자료이고 일부는 2025년 서울 출생 이름 표본입니다. 실제 전국 인기 순위나 세대별 통계는 아닙니다.</p><p>51개 이름에 가능한 한자 표기가 있습니다. 개별 한자와 해당 독음은 공식 조회 자료로 확인했습니다. <strong>이름 전체의 자연스러움·한자 결합 뜻·영어 풀이·명리 해석에 대한 전문가 승인은 아직 없습니다.</strong> 이번 업데이트가 그 검수를 완료했다는 뜻은 아닙니다. 검수 승인 전에는 유료 상세 풀이를 판매하지 않습니다.</p><p>명리 계산은 생년월일과 아는 경우 출생시간을 사용합니다. 시간이 없으면 시주는 배정하지 않습니다. 확인된 한자의 이미지와 일부 사주 정보의 연결이 추천에 영향을 줄 수 있으나, 용신을 정하거나 부족한 오행을 보완한다고 보장하는 작명은 아닙니다.</p>
      <h2>무료와 과금 준비 상태</h2><p>현재 추천·기본 한자·개인 보고서·카드·PDF 인쇄·친구 투표는 모두 무료입니다. 가입·카드 등록·결제가 없습니다. 유료 추가 한자 풀이의 가격안은 해외 US$7.99 / 국내 ₩9,900이며 첫 결제 방식은 무통장입금으로 준비할 예정입니다. 아직 주문·입금 수취·유료 제공은 열지 않았습니다.</p><p><a href="/plans">무료 범위와 향후 유료 계획 보기</a></p>
      <section lang="en" id="quality-en" className="guide-english"><h2>What has been checked?</h2><p>For 51 name forms, we checked the individual Hanja characters and their designated readings against the Korean Supreme Court lookup on September 25, 2026. This does not verify the meaning of the combined name, its full legal registration eligibility, or its traditional element interpretation. English glosses are editorial translations. Whole-name naturalness, combined meanings, English explanations, and traditional interpretations are still awaiting professional review.</p><p>Our default shortlist contains 796 forms screened from a corpus of 2,119. Most source records are synthetic Korean personas; a smaller sample comes from recent Seoul birth-name tables. These counts are not nationwide popularity rankings or verified generation-by-generation statistics. Familiar, timeless, and contemporary are preferences based on limited source signals and editorial notes, not a match to your age.</p><p>A missing Hanja spelling is shown as “Hanja not assigned.” We do not invent a literal meaning for it. We do not calculate a definitive best element or guarantee changes to your fortune. All current beta features are free; an expert-reviewed paid story is not available yet.</p></section>
      <h2>공유 링크를 구분해 주세요</h2><ul className="guide-list"><li><strong>메인 베타:</strong> 새로 이름을 만드는 공개 링크입니다. 팀 배포에는 이 링크를 사용하세요.</li><li><strong>개인 결과·보고서:</strong> 본명·개인 의미 메모·사주 요약이 들어갈 수 있습니다. 링크를 가진 사람은 열 수 있고 7일 후 만료됩니다.</li><li><strong>친구 투표:</strong> 고른 후보 이름·로마자 표기·득표수만 공유합니다. 원래 결과가 만료되거나 삭제되면 투표도 열 수 없습니다.</li><li><strong>PNG 카드:</strong> 선택한 이름·선택 성씨·가능한 한자만 포함합니다. 본명·사주·생일·개인 링크는 제외합니다.</li></ul>
      <section lang="en" className="guide-english"><h2>For English-speaking testers</h2><p>Try the free beta: enter your given name, Gregorian birth date, preferred impression, and an optional meaning. Birth time is optional. Choose a name, open its story, download a card, and ask friends to vote. Please use “Send feedback” to tell us which names or explanations feel unnatural. Do not include personal details in feedback.</p><a className="hero-cta" href="/">Try the free name finder →</a></section>
      <p><a href="/beta-privacy">영어 개인정보 안내</a> · <a href="/">메인 베타로 돌아가기</a></p>
    </article>
  </main>;
}
